replicas: 2

image:
  repository: "opensearchproject/opensearch"
  tag: "2.16.0"
  pullPolicy: "IfNotPresent"

opensearchJavaOpts: "-Xmx512M -Xms512M"

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"


persistence:
  enabled: true
  labels:
    # Add default labels for the volumeClaimTemplate of the StatefulSet
    enabled: false
  storageClass: "nfs-delete"
  accessModes:
    - ReadWriteOnce
  size: 1Gi
